language: android
jdk: oraclejdk8
compiler: gcc
sudo: required

env:
  global:
    - ANDROID_TARGET=android-25
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20
    - GRADLE_USER_HOME="${TRAVIS_BUILD_DIR}/gradle"

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

android:
  components:
  - platform-tools
  - tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-25
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

notifications:
  email: false

before_install:
  - pip install --user codecov
  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

  # Install NDK
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install libstdc++6
  - echo y | $ANDROID_HOME/../android-sdk/tools/bin/sdkmanager "cmake;3.6.3155560"
  - echo y | $ANDROID_HOME/../android-sdk/tools/bin/sdkmanager "ndk-bundle"
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle

branches:
  only:
    - release/sdk
    - deomo

before_script:
  - android list targets
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - adb shell svc power stayon true # Keep emulator awake and disable animations:
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - sleep 30

script:
  - ./execute print-delayed &
  - ./gradlew clean
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew connectedCheck

# after_success:
  # - codecov
