language: android
jdk: oraclejdk8
sudo: false

env:
  global:
    - ANDROID_TARGET=android-25
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - build-tools-25.0.2
  - platform-tools
  - android-25
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

notifications:
  email: false

before_install:
  - pip install --user codecov
  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

  # Install NDK
  - export NDK_VERSION=r10e
  - curl -L http://dl.google.com/android/ndk/android-ndk-${NDK_VERSION}-linux-x86_64.bin -O
  - chmod u+x android-ndk-${NDK_VERSION}-linux-x86_64.bin
  - ./android-ndk-${NDK_VERSION}-linux-x86_64.bin > /dev/null
  - rm android-ndk-${NDK_VERSION}-linux-x86_64.bin
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-${NDK_VERSION}
  - export PATH=${ANDROID_NDK_HOME}:${PATH}

branches:
  only:
    - release/sdk
    - deomo

before_script:
  - ./gradlew clean && ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v

script:
 - ./gradlew connectedCheck

after_success:
  - codecov
